spring.application.name=file_vault
spring.security.user.name=temp
spring.security.user.password=temp
spring.datasource.url=jdbc:postgresql://localhost:5432/file_vault_database
spring.datasource.password=file_vault123
spring.datasource.username=file_vault
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect