spring.application.name=file_vault
spring.security.user.name=temp
spring.security.user.password=temp
spring.datasource.url=jdbc:postgresql://localhost:5432/file_vault_database
spring.datasource.password=file_vault123
spring.datasource.username=file_vault
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
file.storage.base-path = users
file.storage.backup-path= backup
spring.config.import=optional:file:.env[.properties]

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#mail settings
#won't work if antivirus is on!
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#KEK
AES_MASTER_KEY_BASE64=${AES_MASTER_KEY_BASE64}

#HTTPS settings

server.port=8443
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=${SSL_KEY_ALIAS}